
Small reproducer for issue which occurs in Python 3.6 x64 on the windows github
workflow when attempting to `mypycify` a module.

As demonstrated, 3.7 and 3.6 x86 do not exhibit the behavior. Neither does
ubuntu with Python 3.6 x64. I've also personally tested Python 3.6 x64 on a
Windows 10 machine and it works fine.
